namespace StaticRustLauncher.Models;

public static class StaticCollections
{
    public static readonly IReadOnlyDictionary<char, string> СharToTag = new Dictionary<char, string>
    {
        {
          'b',
          "Ежедневно"
        },
        {
          'c',
          "creative"
        },
        {
          'd',
          "training"
        },
        {
          'e',
          "minigame"
        },
        {
          'g',
          "gamemode"
        },
        {
          'h',
          "hardcore"
        },
        {
          'i',
          "battlefield"
        },
        {
          'j',
          "broyale"
        },
        {
          'k',
          "builds"
        },
        {
          'm',
          "Ежемесячно"
        },
        {
          'p',
          "pve"
        },
        {
          'r',
          "roleplay"
        },
        {
          's',
          "softcore"
        },
        {
          't',
          "tut"
        },
        {
          'v',
          "vanilla"
        },
        {
          'w',
          "Еженедельно"
        }
    };
}
